# Generated by Django 5.1.6 on 2025-03-05 06:11

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Showroom',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('phone', models.CharField(max_length=15, unique=True)),
                ('registered_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('approval_status', models.BooleanField(default=False)),
                ('password', models.CharField(max_length=128)),
                ('id_proof_number', models.CharField(max_length=50, unique=True)),
                ('profile_image_showroom', models.ImageField(blank=True, null=True, upload_to='profile_images_showroom/')),
                ('address', models.TextField()),
            ],
        ),
    ]
