# Generated by Django 5.0.4 on 2025-03-27 06:11

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Customer', '0002_vehicle'),
    ]

    operations = [
        migrations.CreateModel(
            name='VehicleFeatures',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('previous_owners', models.PositiveIntegerField(blank=True, default=1, null=True)),
                ('condition', models.CharField(choices=[('New', 'New'), ('Used', 'Used')], max_length=50)),
                ('color', models.CharField(max_length=50)),
                ('seating_capacity', models.PositiveIntegerField()),
                ('engine_capacity', models.CharField(blank=True, max_length=50, null=True)),
                ('fuel_tank_capacity', models.PositiveIntegerField(blank=True, null=True)),
                ('features', models.TextField(blank=True, null=True)),
                ('safety_rating', models.FloatField(blank=True, null=True)),
                ('gps_enabled', models.BooleanField(default=False)),
                ('bluetooth_connectivity', models.BooleanField(default=False)),
                ('negotiable', models.BooleanField(default=True)),
                ('insurance_valid_till', models.DateField(blank=True, null=True)),
                ('warranty_available', models.BooleanField(default=False)),
                ('vehicle', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='features', to='Customer.vehicle')),
            ],
        ),
    ]
