# Generated by Django 5.0.4 on 2025-03-28 15:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Customer', '0004_rentalbooking_testdrivebooking'),
    ]

    operations = [
        migrations.AddField(
            model_name='testdrivebooking',
            name='Contancted',
            field=models.CharField(choices=[('Pending', 'Pending'), ('Contacted', 'Contacted')], default='Pending', max_length=20),
        ),
        migrations.AddField(
            model_name='testdrivebooking',
            name='Intrested',
            field=models.CharField(choices=[('Pending', 'Pending'), ('Intrested', 'Intrested'), ('Not-Intrested', 'Not-Intrested')], default='Pending', max_length=20),
        ),
        migrations.AddField(
            model_name='testdrivebooking',
            name='Payment_amount',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
        ),
    ]
