# Generated by Django 5.0.4 on 2025-03-28 18:56

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Customer', '0005_testdrivebooking_contancted_and_more'),
        ('Dealer', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='testdrivebooking',
            name='dealer',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='Dealer.dealer'),
        ),
        migrations.AlterField(
            model_name='testdrivebooking',
            name='customer',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='Customer.customer'),
        ),
    ]
